project_id = "xtawnkhvxgxylhxwqnmm"

[functions.create-user]
verify_jwt = true

[functions.create-user-manually]
verify_jwt = true

[functions.test-email]
verify_jwt = false

[functions.upload-3d-model]
verify_jwt = false

[functions.xero-oauth]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-activation-email]
verify_jwt = false