project_id = "xtawnkhvxgxylhxwqnmm"

[functions.create-user]
verify_jwt = true

[functions.create-user-manually]
verify_jwt = true

[functions.test-email]
verify_jwt = false

[functions.upload-3d-model]
verify_jwt = false

[functions.xero-oauth]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-activation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = true

[functions.ai-chat]
verify_jwt = false

[functions.analyze-activity]
verify_jwt = false

[functions.optimize-schedule]
verify_jwt = false

[functions.send-user-invitation]
verify_jwt = true

[functions.revoke-user-invitation]
verify_jwt = true

[functions.delete-user-admin]
verify_jwt = true

[functions.platform-management]
verify_jwt = true

[functions.extract-document]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false