-- Clear existing digital objects data
DELETE FROM digital_objects;

-- Insert new data from screenshots
INSERT INTO digital_objects (name, object_type, description, status, stage, level, parent_id, expanded) VALUES
-- 4.0 PRELIMINARY
('Demolition', 'demolition', 'Demolition work', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Site Feature & Re-establishment Services', 'site_work', 'Site preparation and establishment', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Architectural', 'design', 'Architectural design services', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Engineering', 'design', 'Engineering services', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Geotechnical Soil Testing', 'testing', 'Soil testing and analysis', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Energy Report', 'report', 'Energy efficiency report', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Performance Solution Report', 'report', 'Building performance solution report', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Civil Drainage Design', 'design', 'Civil drainage system design', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Roof Drainage Design', 'design', 'Roof drainage system design', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Interior Designer / Interior Documentation', 'design', 'Interior design and documentation', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Landscape Designer / Architect', 'design', 'Landscape design services', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Project Estimate', 'estimate', 'Project cost estimation', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Building Surveying', 'survey', 'Building surveying services', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Domestic Building Insurance', 'insurance', 'Building insurance coverage', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Work Protection Insurance', 'insurance', 'Work protection insurance', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Construction Management Services', 'management', 'Construction management services', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Builders License', 'license', 'Building license and permits', 'planning', '4.0 PRELIMINARY', 0, null, true),
('3D Renders / Virtual Design Models', 'visualization', '3D rendering and virtual models', 'planning', '4.0 PRELIMINARY', 0, null, true),
('Asset Protection', 'protection', 'Asset protection measures', 'planning', '4.0 PRELIMINARY', 0, null, true),
('CONTINGENCY', 'contingency', 'Contingency allowance', 'planning', '4.0 PRELIMINARY', 0, null, true),

-- 4.1 PRE-CONSTRUCTION
('Underground Power', 'utilities', 'Underground power connection', 'planning', '4.1 PRE-CONSTRUCTION', 0, null, true),
('Site Hoarding', 'site_work', 'Site hoarding installation', 'planning', '4.1 PRE-CONSTRUCTION', 0, null, true),
('Fence Hire', 'site_work', 'Temporary fencing hire', 'planning', '4.1 PRE-CONSTRUCTION', 0, null, true),
('PIC Application', 'permit', 'PIC application and approval', 'planning', '4.1 PRE-CONSTRUCTION', 0, null, true),
('Dilapidation Report', 'report', 'Dilapidation survey report', 'planning', '4.1 PRE-CONSTRUCTION', 0, null, true),

-- 5.1 BASE STAGE
('Excavation', 'earthwork', 'Site excavation work', 'planning', '5.1 BASE STAGE', 0, null, true),
('Slab', 'concrete', 'Concrete slab construction', 'planning', '5.1 BASE STAGE', 0, null, true),
('Site Clean', 'cleaning', 'Site cleaning and preparation', 'planning', '5.1 BASE STAGE', 0, null, true),
('Set Out', 'survey', 'Building set out and survey', 'planning', '5.1 BASE STAGE', 0, null, true),
('Protection Works', 'protection', 'Site protection works', 'planning', '5.1 BASE STAGE', 0, null, true),
('Planter Boxes', 'landscaping', 'Planter box installation', 'planning', '5.1 BASE STAGE', 0, null, true),
('Pest Control Part A', 'pest_control', 'Initial pest control treatment', 'planning', '5.1 BASE STAGE', 0, null, true),
('Fence Painting', 'painting', 'Fence painting work', 'planning', '5.1 BASE STAGE', 0, null, true),
('Fence - Rear', 'fencing', 'Rear fence installation', 'planning', '5.1 BASE STAGE', 0, null, true),

-- 5.2 FRAME STAGE
('Windows', 'windows', 'Window installation', 'planning', '5.2 FRAME STAGE', 0, null, true),
('Trusses & Frames', 'structure', 'Roof trusses and frames', 'planning', '5.2 FRAME STAGE', 0, null, true),
('Frame Carpenter', 'carpentry', 'Frame carpentry work', 'planning', '5.2 FRAME STAGE', 0, null, true),
('Structural Steel Detailing', 'structure', 'Structural steel detailing', 'planning', '5.2 FRAME STAGE', 0, null, true),
('Structural Steel', 'structure', 'Structural steel supply and installation', 'planning', '5.2 FRAME STAGE', 0, null, true),
('Skylights', 'windows', 'Skylight installation', 'planning', '5.2 FRAME STAGE', 0, null, true),
('Plumbing', 'plumbing', 'Plumbing rough-in work', 'planning', '5.2 FRAME STAGE', 0, null, true),
('Electrician', 'electrical', 'Electrical rough-in work', 'planning', '5.2 FRAME STAGE', 0, null, true),

-- 5.3 LOCKUP STAGE
('Solar Panels', 'electrical', 'Solar panel installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Sisalation Paper', 'insulation', 'Sisalation paper installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Security / Intercom / CCTV', 'security', 'Security system installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Screens, Louvres & Awnings', 'external', 'External screens and awnings', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Scaffolding', 'access', 'Scaffolding installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Roof Rails', 'roofing', 'Roof rail installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Metal Roof', 'roofing', 'Metal roof installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Mechanical services (HVAC)', 'hvac', 'HVAC system installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Lock up Material', 'materials', 'Lock up materials supply', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Lock up Carpenter', 'carpentry', 'Lock up carpentry work', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Home Automation', 'automation', 'Home automation system', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Brick Supply', 'materials', 'Brick supply', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Brick - Sand & Cement', 'materials', 'Brick sand and cement supply', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Bricklaying Labour', 'bricklaying', 'Bricklaying labor', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Brick Clean', 'cleaning', 'Brick cleaning work', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('Hebel Cladding', 'cladding', 'Hebel cladding installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),
('James Hardie Cladding', 'cladding', 'James Hardie cladding installation', 'planning', '5.3 LOCKUP STAGE', 0, null, true),

-- 5.4 FIXING STAGE
('Timber Floor Supply', 'materials', 'Timber flooring supply', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Timber Floor Installation', 'flooring', 'Timber floor installation', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Floor Tile Supply', 'materials', 'Floor tile supply', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Wall Tile Supply', 'materials', 'Wall tile supply', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Waterproofing', 'waterproofing', 'Waterproofing work', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Tiling Labour', 'tiling', 'Tiling labor work', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Stone Benchtops', 'stonework', 'Stone benchtop installation', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Stairs', 'carpentry', 'Stair construction', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Sound Proofing', 'insulation', 'Sound proofing installation', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Plumbing Fixtures', 'plumbing', 'Plumbing fixture installation', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Plaster', 'plastering', 'Plastering work', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Painter', 'painting', 'Painting work', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Joinery', 'joinery', 'Joinery work', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Insulation', 'insulation', 'Insulation installation', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Hydronic In-Slab Heating', 'heating', 'Hydronic heating system', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Fixing Materials', 'materials', 'Fixing materials supply', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Fix Carpenter', 'carpentry', 'Fix carpentry work', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Fit Off Carpenter', 'carpentry', 'Fit off carpentry work', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Doors & Frames', 'doors', 'Door and frame installation', 'planning', '5.4 FIXING STAGE', 0, null, true),
('Door Hardware', 'hardware', 'Door hardware installation', 'planning', '5.4 FIXING STAGE', 0, null, true),

-- 5.5 FINALS
('Window Furnishing', 'furnishing', 'Window furnishing installation', 'planning', '5.5 FINALS', 0, null, true),
('Splashback', 'tiling', 'Kitchen splashback installation', 'planning', '5.5 FINALS', 0, null, true),
('Showers & Mirrors', 'bathroom', 'Shower and mirror installation', 'planning', '5.5 FINALS', 0, null, true),
('Pest Control: Part B', 'pest_control', 'Final pest control treatment', 'planning', '5.5 FINALS', 0, null, true),
('Garage Door', 'doors', 'Garage door installation', 'planning', '5.5 FINALS', 0, null, true),
('Caulking', 'finishing', 'Caulking work', 'planning', '5.5 FINALS', 0, null, true),
('Carpet Floor coverings', 'flooring', 'Carpet installation', 'planning', '5.5 FINALS', 0, null, true),
('Builders Clean', 'cleaning', 'Final builders clean', 'planning', '5.5 FINALS', 0, null, true),
('Appliances', 'appliances', 'Appliance installation', 'planning', '5.5 FINALS', 0, null, true),

-- 5.6 LANDSCAPING
('Pool Fence/Gate', 'pool', 'Pool fence and gate installation', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Pool', 'pool', 'Pool construction', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Paving & Pool Surround', 'paving', 'Paving and pool surround', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Outdoor Lighting', 'lighting', 'Outdoor lighting installation', 'planning', '5.6 LANDSCAPING', 0, null, true),
('New Cross-Over & Pavements', 'paving', 'Crossover and pavement work', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Letter Box', 'external', 'Letter box installation', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Lawn Area', 'landscaping', 'Lawn installation', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Driveway', 'paving', 'Driveway construction', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Decking Areas', 'decking', 'Decking construction', 'planning', '5.6 LANDSCAPING', 0, null, true),
('Clothes Lines', 'external', 'Clothes line installation', 'planning', '5.6 LANDSCAPING', 0, null, true),

-- 6.0 HANDOVER & CLOSE-OUT
('Perform final walk-through inspection', 'inspection', 'Final walk-through inspection', 'planning', '6.0 HANDOVER & CLOSE-OUT', 0, null, true),
('Maintenance Manuals & Warranties', 'documentation', 'Maintenance manuals and warranties', 'planning', '6.0 HANDOVER & CLOSE-OUT', 0, null, true),
('Final read for gas, water and electricity', 'utilities', 'Final utility readings', 'planning', '6.0 HANDOVER & CLOSE-OUT', 0, null, true),
('Complete punch list items', 'finishing', 'Complete remaining punch list items', 'planning', '6.0 HANDOVER & CLOSE-OUT', 0, null, true),
('Complete final inspection for certification', 'inspection', 'Final inspection for certification', 'planning', '6.0 HANDOVER & CLOSE-OUT', 0, null, true);